name: "Building .NET Project"
description: "Restores, builds, and optionally uploads a .NET project."

inputs:
  project-name:
    description: "Name of the .NET project."
    required: true
  app-dir:
    description: "Path to the .csproj file."
    required: true
  build-configuration:
    description: "Build configuration (e.g., Release, Debug)."
    required: false
    default: "Release"
  upload_build:
    description: "Set to true to upload the build artifacts."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: 📥 Checkout source code
      uses: actions/checkout@v4

    - name: 🔧 Restore NuGet packages
      shell: bash
      run: |
        dotnet restore "${{ inputs.app-dir }}"

    - name: 🛠️ Build .NET project
      shell: bash
      run: |
        output_dir="./dotnet_build_output-${{ inputs.project-name }}"
        log_file="${{ inputs.project-name }}/build.log"

        mkdir -p "${{ inputs.project-name }}"
        dotnet build "${{ inputs.app-dir }}" \
          --configuration "${{ inputs.build-configuration }}" \
          --no-restore \
          -o "${output_dir}" \
          -fl -flp:logfile="${log_file};verbosity=diagnostic"

    - name: 📝 Annotate warnings and errors
      shell: bash
      run: |
        log_file="${{ inputs.project-name }}/build.log"
        awk '
        /: warning [A-Z0-9]+:/ {
            print "::warning title=Build Warning::" $0
        }
        /: error [A-Z0-9]+:/ {
            print "::error title=Build Error::" $0
        }
        ' "${log_file}"

    - name: 📦 Upload build artifacts
      if: ${{ inputs.upload_build == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ inputs.project-name }}
        path: ./dotnet_build_output-${{ inputs.project-name }}
        if-no-files-found: ignore
