name: Build 03-app-dotnet from github-actions-course

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo (ukhare/github-actions)
        uses: actions/checkout@v4

      - name: Checkout remote repo (ukhare/github-actions-course)
        uses: actions/checkout@v4
        with:
          repository: ukhare/github-actions-course
          path: github-actions-course
          token: ${{ secrets.GH_PTA }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Run Build Action
        uses: ./.github/actions/dotnet-build-action
        with:
          project-name: 03-app-dotnet
          app-dir: github-actions-course/03-app-dotnet/app-dotnet.csproj
          build-configuration: Release
          upload_build: true
