name: Build Multiple .NET Projects

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
  workflow_dispatch:
    inputs:
      run_test:
        description: 'Run the test for dotnet-build-action'
        required: true
        default: 'true'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix based on event
        id: set-matrix
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

          run_test="false"
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            run_test=$(jq -r '.inputs.run_test // "false"' "$GITHUB_EVENT_PATH" | tr -d '[:space:]')
          fi

          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" && "$run_test" == "true" ]]; then
            matrix='[
              {"project-name":"test-app-dotnet-01", "app-dir":"test-app-dotnet-01"},
              {"project-name":"test-app-dotnet-02", "app-dir":"test-app-dotnet-02"}
            ]'
          elif [[ "$GITHUB_EVENT_NAME" == "push" || "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            matrix='[
              {"project-name":"my-app-dotnet-01", "app-dir":"my-app-dotnet-01"},
              {"project-name":"my-app-dotnet-02", "app-dir":"my-app-dotnet-02"}
            ]'
          else
            matrix='[]'
          fi

          echo "matrix=$(echo "$matrix" | jq -c .)" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare-matrix
    if: ${{ fromJson(needs.prepare-matrix.outputs.matrix) != '[]' }}
    runs-on: [self-hosted, medium-amd64]
    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Create .NET Project - ${{ matrix.project-name }}
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_test == 'true'
        shell: bash
        run: |
          rm -rf "${{ matrix.project.app-dir }}"
          dotnet new console -n "${{ matrix.project-name }}" -o "${{ matrix.app-dir }}"

      - name: Build ${{ matrix.project-name }}
        uses: ./.github/actions/dotnet-build-action
        with:
          project-name: ${{ matrix.project-name }}
          app-dir: ${{ matrix.app-dir }}/${{ matrix.project-name }}.csproj
          build-configuration: Release
          upload_build: true
