name: Build .NET App

on:
  push:
    paths:
      - '03-app-dotnet/**'
      - '.github/workflows/dotnet-build.yml'
  pull_request:
    paths:
      - '03-app-dotnet/**'
      - '.github/workflows/dotnet-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom .NET build action
        uses: ./.github/actions/dotnet-build
        with:
          project_path: 03-app-dotnet/app-dotnet.csproj
          configuration: Release
